export const CURRENT_SELECT_DIR = 'CURRENT_SELECT_DIR'
export const CURRENT_SELECT_STAT = 'CURRENT_SELECT_STAT'
export const CURRENT_DESELECT_DIR = 'CURRENT_DESELECT_DIR'
export const CURRENT_DESELECT_STAT = 'CURRENT_DESELECT_STAT'
