export const STAT_INIT = "STAT_INIT"
export const STAT_LOADING = 'STAT_LOADING'
export const STAT_READY = 'STAT_READY'


export const STAT_SELECTED_INIT = "STAT_SELECTED_INIT"
export const STAT_SELECTED_LOADING = 'STAT_SELECTED_LOADING'
export const STAT_SELECTED_READY = 'STAT_SELECTED_READY'


export const STAT_CREATE = 'STAT_CREATE'
export const STAT_EDIT = 'STAT_EDIT'
export const STAT_SAVE = 'STAT_SAVE'
export const STAT_DELETE = 'STAT_DELETE'
export const STAT_END_EDITING = 'STAT_END_EDITING'
export const STAT_EDIT_ERROR = 'STAT_EDIT_ERROR'


export const STAT_DIR_SELECTED = "STAT_DIR_SELECTED"
export const STAT_ITEM_SELECTED = "STAT_ITEM_SELECTED"
